### ISSUE TITLE
Vsoft Employee Portal UI development and API Integration

### ISSUE THREAD

**Issue by vsoftsol10** [vsoftsol10/vsoft_employee_portal#1]
currently i have finished basic outline of the page

**Comment by VijayAnandan18** [comment]
Today i have done arranged admin ui in the morning and after that i have created the db structure and i have done posting of data in the firebase and you check that too and i have updated in git

**Comment by VijayAnandan18** [comment]
Today I have done admin and user posting of data in firebase and I am doing fetching of data from firebase to admin and user and I have updated in git ticket and uploaded in git

**Comment by VijayAnandan18** [comment]
i uploaded in git and in whatsapp i have sent video

**Comment by VijayAnandan18** [comment]
sir i have updated my code in git repo and today i have did the correction what i have sent through a voice message and today fetching and posting of data from files page is over and profile page fetching and posting of data is over and i have setup the firebase cloud messaging feature for notification and balance-leave page,payroll,tasks page thats all and i can try to finish the end level and after that if found you try to rectify that

**Comment by VijayAnandan18** [comment]
today i have finished the payroll page in both admin and user page both fetching and posting of pdf and im working on leave page fetching and tommorow we will see

**Comment by VijayAnandan18** [comment]
today i have deploy the website in netlify and still there are some updates are there and that are to be updated tommorow

**Comment by VijayAnandan18** [comment]
today i have implemented a new idea to calculate the attendance and leave and marking it in the attendance calendar and i think  if this issue finished we can launch

**Comment by VijayAnandan18** [comment]
today i have done build file to deploy for review for audience and only message and faq page is balance all other things are finished

**Comment by VijayAnandan18** [comment]
today i am not updated any code in git as it have issues and i have just update in ticket and in whatsapp

**Comment by VijayAnandan18** [comment]
Today i have worked in dashboard and directory page for latest modifications and updated my code in git

**Comment by VijayAnandan18** [comment]
today i have finished the directory of admin page it have features of importing  file from xlsx and bulk  creating users and when i give the xlsx it also generates userid and sends email to the user party and and in the dashboard i created some fetching in cards.

**Comment by VijayAnandan18** [comment]
Today i have done a dashboard,directory and tasks pages ui and still more in css for arrangement and i have updated my code in git

**Comment by VijayAnandan18** [comment]
today i have done   attendance page fetching for auto marking in the calendar and leave tracker page fetching in that and pie chart  in the admin dashboard page

**Comment by VijayAnandan18** [comment]
today i have done my work leave tracker page for handling email and slightly worked in the dashboard and  i have pushed my code in master branch

**Comment by VijayAnandan18** [comment]
Today i have done mail fetching for leave tracker if i apply leave and accepting leave it will send a mail

**Comment by VijayAnandan18** [comment]
Today i have done the user dashboard page and corrections in vsoft website and i have updated in git

**Comment by VijayAnandan18** [comment]
Today i have done the admin login and user login  by refering figma designs and i  have updated in git

**Comment by VijayAnandan18** [comment]
todays work  i have done mobile responsive for the page![Image](https://github.com/user-attachments/assets/00e3a156-7309-4f5d-acdd-476a9cee7259)
![Image](https://github.com/user-attachments/assets/fae58c34-59d1-4ff1-942c-43cfcdf32f09)

**Comment by VijayAnandan18** [comment]
Today i have done some corrections and learning redux

**Comment by VijayAnandan18** [comment]
Today i have learned redux (immutability, functional programming

**Comment by VijayAnandan18** [comment]
Today i have worked in user dashboard ui for making it more attractive by adding weather api and cover photo like features.
![Image](https://github.com/user-attachments/assets/dbef3bdf-a529-4b0c-b2fd-595d77b6760e)

**Comment by VijayAnandan18** [comment]
today i have done ui for user dashboard and sidebar for both admin and user and i havent updated in git ,due to i have made some pending work in leave tracker page![Image](https://github.com/user-attachments/assets/5093f6b2-7c90-422d-83b3-a1708a5dfe4d)

**Comment by VijayAnandan18** [comment]
Today i have done the leave pages ui but i cant make it look alike the figma design and i have issues sir i will describe that in the voice![Image](https://github.com/user-attachments/assets/2a6f4970-1a46-4ce6-a6b4-6e18338105ba)

**Comment by VijayAnandan18** [comment]
Today i have done some corrections in hrms and in smec website and tried smec website deploying

**Comment by VijayAnandan18** [comment]
Today i have done hrms portal leave tracker page issues and tried attendance ui and trying to solve git issues

**Comment by VijayAnandan18** [comment]
![Image](https://github.com/user-attachments/assets/11fa7328-58c6-4cc1-b8e0-353040c1eb4c)
![Image](https://github.com/user-attachments/assets/457d16b9-3329-40db-8bfe-18978167f658)
![Image](https://github.com/user-attachments/assets/d9926ab0-1c4f-4d1b-8d46-2d688cfff779)![Image](https://github.com/user-attachments/assets/0cfcc2c7-2601-4d02-9987-985bc9d2459d)
![Image](https://github.com/user-attachments/assets/90e06751-4fd0-4ef6-9a1b-6622844ee6e4)

Today I have done ui for this pages and i have done client suggestions in smec and i have pushed both the code in git
